---
- hosts: all

  become: true
  become_method: sudo
  become_user: root  
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: Instalar Midnight Commander (mc)
      apt:
        name: mc
        state: present
      become_user: root
