---
- hosts: all
  become: true
  become_method: sudo
  become_user: root  
  tasks:
    - name: Update the package index
      command: sudo apt update
      register: result

    - name: Mostrar la salida del comando ls
      debug:
        var: result.stdout_lines