---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Update the package index
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Check if Docker GPG key file exists
      stat:
        path: /usr/share/keyrings/docker-archive-keyring.gpg
      register: keyfile

    - name: Download Docker GPG key if it doesn't exist
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg
      when: not keyfile.stat.exists

    - name: Import Docker GPG key
      command: gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
      when: not keyfile.stat.exists

    - name: Agregar el repositorio de Docker al sistema
      shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null


    - name: Update package index after adding repository
      apt:
        upgrade: yes
        update_cache: yes
        
    - name: Install Docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        append: yes
        groups: docker

    - name: Verify Docker installation
      command: docker run hello-world

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system|lower }}-{{ 'x86_64' if ansible_architecture == 'x86_64' else 'arm64' }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker-compose --version
