---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Verificar si la clave Docker GPG ya existe
      stat:
        path: /usr/share/keyrings/docker-archive-keyring.gpg
      register: keyfile

    - name: Descargar clave Docker GPG si no existe
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
      when: not keyfile.stat.exists

    - name: Importar clave Docker GPG
      command: gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
      when: not keyfile.stat.exists

    - name: Mostrar mensaje de éxito
      debug:
        msg: "Clave GPG importada correctamente"
