- hosts: all
  become: true
  become_method: sudo
  become_user: root  
  tasks:
    - name: Agregar la clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Instalar dependencias para apt
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Agregar el repositorio de Docker al sistema
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker
        keyserver: hkp://keyserver.ubuntu.com:80
        key: 0EBFCD88

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Instalar Docker Compose
      command: >
        curl -sSL https://github.com/docker/compose/releases/latest/download/docker-compose-{{ 'Linux' if ansible_architecture == 'x86_64' else 'ARMv7' }}
        -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
