- hosts: all
  become: true
  become_method: sudo
  become_user: root  
  tasks:
    - name: Agregar la clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Agregar el repositorio de Docker al sistema
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        create: yes

    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present