---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Import Docker GPG key
      command: gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Mostrar la salida del comando ls
      debug:
        msg: "GPG key imported successfully"
