- hosts: all
  become: true
  become_method: sudo
  become_user: root  
  tasks:
    # - name: Agregar la clave GPG oficial de Docker
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    # - name: Agregar el repositorio de Docker al sistema
    #   apt_repository:
    #     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu"
    #     state: present
    #     filename: docker

    - name: Update the package index
      command: sudo apt update
      register: result

    - name: Mostrar la salida del comando ls
      debug:
        var: result.stdout_lines

    # - name: Instalar dependencias de Docker
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - apt-transport-https
    #     - ca-certificates
    #     - curl
    #     - software-properties-common

    # - name: Instalar Docker
    #   apt:
    #     name: docker-ce
    #     state: present