---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Incluir el playbook Install Net
      include: tools/install_net.yml

    - name: Incluir el playbook Install MySQL
      include: docker/install_mysql.yml