---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Incluir el playbook Install Net
      import_tasks: tools/install_net.yml

    - name: Incluir el playbook Install MySQL
      import_playbook: docker/install_mysql.yml